version: "3.5"

################################################
# Taiga's Settings (edit here)
################################################

# Taiga's URLs settings
x-taiga-scheme: &taiga-site-scheme
  http
x-taiga-domain: &taiga-site-domain
  localhost:9000
x-taiga-subpath: &taiga-site-subpath
  '' # '' or '/subpath'
x-taiga-api-url: &taiga-api-url
  http://localhost:9000
x-taiga-websockets-url: &taiga-websockets-url
  ws://localhost:9000
x-taiga-gateway-ports: &taiga-gateway-ports
  9000:80

# Taiga's Secret Key
x-taiga-secret-key: &taiga-secret-key
  taiga-back-secret-key

# Taiga's Database settings
x-taiga-database-settings: &default-db-settings
  POSTGRES_DB: taiga
  POSTGRES_USER: taiga
  POSTGRES_PASSWORD: taiga
  POSTGRES_HOST: taiga-db
#  POSTGRES_PORT: 5432

# Taiga's SMTP Settings
x-taiga-email-settings: &default-email-settings
  # Uncomment following lines and configure your SMTP server
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  DEFAULT_FROM_EMAIL: "60327312eb9a61@inbox.mailtrap.io"
  EMAIL_USE_TLS: "True"
  EMAIL_USE_SSL: "False"
  EMAIL_HOST: "smtp.mailtrap.io"
  EMAIL_PORT: 25
  EMAIL_HOST_USER: "60327312eb9a61"
  EMAIL_HOST_PASSWORD: "cb8cf1dbee3f63"

# Taiga's RabbitMQ settings
x-taiga-rabbitmq-user: &default-rabbitmq-user
  taiga
x-taiga-rabbitmq-pass: &default-rabbitmq-pass
  taiga
x-taiga-rabbitmq: &default-rabbitmq-settings
  RABBITMQ_USER: *default-rabbitmq-user
  RABBITMQ_PASS: *default-rabbitmq-pass

# Taiga's Volume settings
x-taiga-volumes: &default-volumes
  - taiga-static-data:/taiga-back/static
  - taiga-media-data:/taiga-back/media
  # - ./config.py:/taiga-back/settings/config.py

# Taiga's Telemetry settings
x-taiga-telemetry: &taiga-enable-telemetry
  'True'

################################################
# Docker compose services (do NOT touch)
################################################
services:
  taiga-db:
    image: postgres:12.3
    environment: *default-db-settings
    volumes:
      - taiga-db-data:/var/lib/postgresql/data
    networks:
      - taiga

  taiga-back:
    image: taigaio/taiga-back:latest
    environment:
      <<: *default-db-settings
      <<: *default-email-settings
      <<: *default-rabbitmq-settings
      TAIGA_SECRET_KEY: *taiga-secret-key
      TAIGA_SITES_SCHEME: *taiga-site-scheme
      TAIGA_SITES_DOMAIN: *taiga-site-domain
      TAIGA_SUBPATH: *taiga-site-subpath
      ENABLE_TELEMETRY: *taiga-enable-telemetry
    volumes: *default-volumes
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-events-rabbitmq
      - taiga-async-rabbitmq

  taiga-async:
    image: taigaio/taiga-back:latest
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment:
      <<: *default-db-settings
      <<: *default-email-settings
      <<: *default-rabbitmq-settings
      TAIGA_SECRET_KEY: *taiga-secret-key
      TAIGA_SITES_SCHEME: *taiga-site-scheme
      TAIGA_SITES_DOMAIN: *taiga-site-domain
      TAIGA_SUBPATH: *taiga-site-subpath
      ENABLE_TELEMETRY: *taiga-enable-telemetry
    volumes: *default-volumes
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-back
      - taiga-async-rabbitmq

  taiga-async-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: *default-rabbitmq-user
      RABBITMQ_DEFAULT_PASS: *default-rabbitmq-pass
      RABBITMQ_DEFAULT_VHOST: taiga
    volumes:
      - taiga-async-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga

  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: *taiga-api-url
      TAIGA_WEBSOCKETS_URL: *taiga-websockets-url
      TAIGA_SUBPATH: *taiga-site-subpath
    networks:
      - taiga
    # volumes:
    #   - ./conf.json:/usr/share/nginx/html/conf.json

  taiga-events:
    image: taigaio/taiga-events:latest
    environment:
      <<: *default-rabbitmq-settings
      TAIGA_SECRET_KEY: *taiga-secret-key
    networks:
      - taiga
    depends_on:
      - taiga-events-rabbitmq

  taiga-events-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: *default-rabbitmq-user
      RABBITMQ_DEFAULT_PASS: *default-rabbitmq-pass
      RABBITMQ_DEFAULT_VHOST: taiga
    volumes:
      - taiga-events-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga

  taiga-protected:
    image: taigaio/taiga-protected:latest
    environment:
      MAX_AGE: 360
      SECRET_KEY: *taiga-secret-key
    networks:
      - taiga

  taiga-gateway:
    image: nginx:1.19-alpine
    ports:
      - *taiga-gateway-ports
    volumes:
      - ./taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - taiga-static-data:/taiga/static
      - taiga-media-data:/taiga/media
    networks:
      - taiga
    depends_on:
      - taiga-front
      - taiga-back
      - taiga-events

volumes:
  taiga-static-data:
  taiga-media-data:
  taiga-db-data:
  taiga-async-rabbitmq-data:
  taiga-events-rabbitmq-data:

networks:
  taiga:
